/** Generated by scripts/gen-doc-catalog.py. Do not edit by hand. */
export const REGIONAL_DOCUMENT_COVERAGE = {
  sourceRecords: 1037,
  saldoRecords: 109,
  saldoMunicipalities: 71,
  counties: ["York", "Cumberland", "Dauphin", "Lancaster"] as const,
} as const;
